# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MapDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapDemo
pod 'GoogleMaps'
pod 'RSKImageCropper'
pod 'QBImagePickerController'

 

  target 'MapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MapDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapDemo-tvOS

  target 'MapDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
